# Assignment 1 Solutions

Problem Statement 1: Write a Python program to multiply a MxN matrix by NxA matrix and create a real matrix product.

In [1]:
import numpy as np
m=int(input("Enter value M: "))
n=int(input("Enter value N: "))
a=int(input("Enter value A: "))
print("First array:")
arr1=np.random.rand(m,n)
print(arr1)
print("Second array:")
arr2=np.random.rand(n,a)
print(arr2)
print("Dot product of two arrays:")
result=np.dot(arr1,arr2)
print(result)

Enter value M: 5
Enter value N: 3
Enter value A: 2
First array:
[[0.57027706 0.52944552 0.77472464]
 [0.9202183  0.44981639 0.47707528]
 [0.35719698 0.70245539 0.38418287]
 [0.22269474 0.03239819 0.08242502]
 [0.97487726 0.13388445 0.80400785]]
Second array:
[[0.60118825 0.51477399]
 [0.60226938 0.14972428]
 [0.93896233 0.77980434]]
Dot product of two arrays:
[[1.38914995 0.97696829]
 [1.27209079 0.91307826]
 [0.99854324 0.58863781]
 [0.23078789 0.18376364]
 [1.42165234 1.14885602]]


Problem Statement2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

In [2]:
import numpy as np
elements=int(input("Enter no. of elements:"))
arr=[]
for i in range(elements):
    print("Enter your input")
    item=input()
    arr.append(item)
arr=np.array(arr)
print("Input: Original Array:")
print(arr)
print("Digits only:")
digit_arr=np.char.isdigit(arr)
print(digit_arr)
print("Lower case only:")
lower_arr=np.char.islower(arr)
print(lower_arr)
print("Upper case only:")
upper_arr=np.char.isupper(arr)
print(upper_arr)

Enter no. of elements:6
Enter your input
Python
Enter your input
PHP
Enter your input
JS
Enter your input
Examples
Enter your input
html5
Enter your input
5
Input: Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only:
[False False False False False  True]
Lower case only:
[False False False False  True False]
Upper case only:
[False  True  True False False False]
